# Generated by Django 5.0.6 on 2024-07-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0003_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(default=1, upload_to='property_images/'),
            preserve_default=False,
        ),
    ]
