# Generated by Django 5.0.6 on 2024-08-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0006_alter_vehicle_fuel_consumption_rate_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
