# Generated by Django 5.0.6 on 2024-08-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0007_remove_property_latitude_remove_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sale_or_rent',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
