# Generated by Django 5.0.6 on 2024-09-06 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0008_property_sale_or_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='commute_cost',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='property',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='date_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='date_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='CostEstimation',
        ),
    ]
