# Generated by Django 5.0.6 on 2024-09-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0009_remove_historicaldata_commute_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='other_locations',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RealEstate.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='total_effective_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='transportation_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='vehicle_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='work_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='work_trips_per_week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
