# Generated by Django 5.0.6 on 2024-09-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0010_historicaldata_other_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_general_user',
            field=models.BooleanField(default=True),
        ),
    ]
