# Generated by Django 5.0.6 on 2024-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0011_user_is_general_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_general_user',
            new_name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='agent_passports/'),
        ),
        migrations.AddField(
            model_name='user',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
